using Shouldly;
using Xunit;

namespace HandsOn.Algorithm.DynamicProgrammingRecursion
{
    public class PermutationStringTests
    {
        [Fact]
        public void should_check_if_has_permutations()
        {
            PermutationStrings.IsInclusion("ab", "eidabooo").ShouldBeTrue();
        }

        [Fact]
        public void should_check_if_has_permutations_2()
        {
            PermutationStrings.IsInclusion("ab", "eidboaoo").ShouldBeFalse();
        }

        [Fact]
        public void should_check_if_has_permutations_3()
        {
            PermutationStrings.IsInclusion("ab", "a").ShouldBeFalse();
        }

        [Fact]
        public void should_check_if_has_permutations_4()
        {
            PermutationStrings.IsInclusion("plasma", "altruism").ShouldBeFalse();
        }

        [Fact]
        public void should_check_if_has_permutations_5()
        {
            PermutationStrings.IsInclusion("adc", "dcda").ShouldBeTrue();
        }

        [Fact]
        public void should_check_if_has_permutations_6()
        {
            PermutationStrings.IsInclusion("adc", "ccccbbbbaaaa").ShouldBeFalse();
        }

        [Fact]
        public void should_check_if_has_permutations_7()
        {
            PermutationStrings.IsInclusion("hello", "ooolleoooleh").ShouldBeFalse();
        }

        [Fact]
        public void should_check_if_has_permutations_8()
        {
            PermutationStrings.IsInclusion(
                    "nlrsecrfraocbgnsazsngoqjljquksbcspyuqobkpuagfbndhpstpfzatxcwscjwqnjjtlogljhyhtgrpauxnuzlrhljgdlgdpxyahgmdwytivtqccpdukhseoajdmsaozhtnrsjvyzpigvbrxdxqresnuhyzgupaijresrlhtnjkyfwpxairirkzuajnpayhbhyerfqnmwdgqmjzvrdvlsnmxitnumipyfixlzchjwgvfzpsryxxotnuoftqffmiozywskuvnjkuehevohverpbisoblzurysiaqrsqwqfncuqkqbecvrxbkrjiddmfauvetruxwqnelbufekkkwofupyssmkkobatpjthrxgwlpttfupiormualobswtzwwcnrqyxlqfrnvgeeezsacljnewfvvbtzfrvdllqrlvguiinpdxkbhqzgqafzsvvhpijjsqgnyxeoqldfrbbuadzpskrhpziuaoqrvwpionmiojuhxgkufkgaavdeujuxpmggngquxnyqhrdvpxnjwqtlnwnroswrzxxdksfvrnclwonklpomzhwldjjtyylkhgayuuzlbdgacoyhlajtpvgubvwvzmvnuibfcpncqiopzodxbbjohfswkbzgbgtubxqzjnhupkjgyduvfejonadaanactccvfebgaseupnffzflxlgafohudsieixlljnvqeyuruegqslxihourfpbmnhnbgpzxrbxvazmspkdafriouzowmxeqmbyssxgfesetheaafqvotcldddqubagloyblytrzfmkivuudpwektheznegopcdbcldnlzujzmripflhahfgtbqaqvpgyefzpdraamixdyghihyhnofzoywmhkmunvntpyqvajuqholxmdvsmcihsuqivqfbsqerzbtptadkeajuurzufdregtlrotyrozdyyjavpevabtveksdbyfwhmtxvbxbuhxpuutmqfxrrpazbpijaskmhnunntpojdfkppmrhwvvnicthcxhnpjmrgmuwuwqfhwgssdmcgiekgftestjzupqjnakclpmzazaghkosnutqekzlixovhabfsspqbwfvvenygtvmwmrqxnsqejekhzcziwgtyovpyukgcpjzxeqxjvaiffwlgiyzsmztqhmxoqolhblqhxeararaljnswlwdcfxlmehqraoobydhprasgtsesugkyqbexiilmvupjvkbmsmjqgtsyltpaeyhbwbbhrpgazokrlzcibhnbpomieavawiomsfzzkwkndihwzhrpiafrsyufpzblzpvflywmaweprthnkajvplkwfjvcsiblvucjmwcjkwsszhggczzcsfrzgadkasghstkknguodxxhzftrfrnlbrwpwrjlsecvrarjvgciymaincafmlphlibteuzhrfnldcajimjxqomljxweqhyiqtcyznpnsuzzldrladelaqopgiagjhjnsdrmlrldzebcvqxqdthxvhmzcmyczekvymbnyisppljimozszqqxymqkejfewxxihupebmydhlqldrzafehscklchzjlctmuaytuhosxruqanpchvjptbykpezxikaueufuiiujmanodulozjamqduqekihdmeizqcdtfihvijrxoazgibfhoumqriiorsbbkoscxviabqddeqfayfzqptamhojdmxbpyubixhgdhqtmtcvjzdutvbiycsmchgkaeiaxbpgkpreuhoisfptugogaquijkxnyntfututflaacniiawxbxdsghavtenvatfyfkjkeisactvkmweoeubudbekwkbhctxlqabxawclzftxqyvmdaptphftdyfspdwruohjdwsbjtjkmyaabxwrosyeswoygiilbmefqhmuhkvmgljiucorrximtkwdlcmceytuyyrmcbembghmrdzcgxgbzbcscezqamnhnkuecjehouthtpqzeuibiruvneafgizllkntztgksnvtcqklhcyvvrixabwekbjdvezwfjmdrmhiabvnwwanjxbiwhmtgjfjhofpqliigrxnfehmrpjsxsmxvgrwnmpvfxaxzkrzbqccmwizqgaousmehamsdmvibzeslwbolrfxcggviotkytewihiffdwsujqmszzoxhrnktdwefkxtnratgtgnjxjhscuqysuaeuecmsdjdbuvtemhsyygvryfqrlccstckgmtfxtiumvvgwbxotlyogvsmahfcubuywihnchkxhfexfsxteysobunucuqtjwmnnujihqecemszblrzyxmaupkjzgonsvszcslpcwluijfdrfqplpaxjcmhnwbtrlypqpguhhqosmldjtupwhfqlmwikvfruqylvkbwdfmtgcvmidiqtwigrcwdphloerrcsufbgjrulwweolbryzjbnydbjsulwawtibpxfxgtnoiomfnwjdqvjuzwfcbubuoyunlbsrdjvmccyutjksduphzyzeuxdnmejlcwzhktaudwaqqragthmvclwvrrlwfqxbstmotxjelykcthiwoeobyuvirzpvkyhuxqbfwfyspzghjddvjjrctqpvuckeessrlwzznhlmfnxxuhsrntxqysyzvfumrjjybfvhubeofcfsdimcjcunfconixdcckquifqetcoevhtzqqgtrgjlhfrxfrmzrkdrehbjmcsegbgnfwvfwqtjfalftldgzemgsntnpohnmjjfrlkkktxmjynayhqwfiqvjdqdcqhjhcgnviefsrblfvmrjdgmwkajeftvfvrlnswjcvmismwxoqzqrpelaswotetaruqvmqrfjfgcnmtafpvjkrfdhibwvbrvlypvpfjnyxllldutrqkuiikkxkccnvxkkcdmlvsoududwmszpcrxf",
                    "ydwhfwwwyfuwmxkpycqwrqjwfcfpvzdzienbviuczgkoumcpeikpgtdujaraegbcqeaeetxtzbddnllxpbhgurcgcpreyfozxkuqnrabglvzugxipaepgpvplckcuvpvsmluamgwnzlilgmdpotxzyiidrmrmhyqdztpqpcirpibopxydmludvbwwoltspjcqaawalrxdxnfdnzixvhpzymajcnhwtcskauevlktuuyvtkgbzheoqcciqjsdxysmwrfamvygiofgvdesdggcccezkimvhqolyvcakalmrwmfxqdszmcaenthsbrnmvmhrjktetxziceojghzorqunkiteidnlqqfjsmfmwydydvffbiefrzcnmrqveccplbkiyybimwqznlrsecrfraocbgnsazxngoqjljquksbcspyuqobkpuagfbndhpstpfzatxcwscjwqnjjtlogljhyhtgrpauxnuzlrhljgdlgdpxyahgmdwytivtqccpdukhseoajdmsaozhtnrsjvyzpigvbrxdxqresnuhyzgupaijresrlhtnjkyfwpxairirkzuajnpayhbhyerfqnmbdgqmjzvrdvlsnmxitnumipyfixlzchjwgvfzpsryxxotnuoftqffmiozywskuvnjkuehevohverpbisoblzurysiaqrsqwqfncuqkqbecvrxakrjiddmfauvetruxwqnelbufekkkwofupyssmkkobatpjthrxgwlpttfupiormualobswtzwwcnrqyxlqfrnvgeeezsacljnewfvvbtzfrvdllqrlvguiinpdxkbhqzgqafzsvvhpinjsqgnyxeoqldfrbbuadzpskrhpziuaoqrvwpionmiojuhxgkufkgaavdeujuxpmggngquxnyqhrdvpxnjwqtlnwnroswrzxxdksfvrnclwonklpomzhwldjjtyylkhgayuuzlbdgacoyhlajtpvgubvwvzmvnuibfcpncqiopzodxbbjohfswkbzgbgtubxqzjnhupkjgyduvfejonadaanactccvfebgaseupnffzflxlgafohudsieixlljnvqeyuruegqslxihourfpbmnhnbgpzxrbxvazmspkdafriouzowmxeqmbyssxgfesetheaafqvotclddrqubagloyblytrzfmkivuudpwektheznegopcdbcldnlzujzmripflhahfgtbqaqvpgyefzpdraamixdyghihyhnofzoywmhkmunvntpyqvajuqholxmdvsmcihsuqivqfbsqerzbtptadkeajuurzufdregtlrotyrozdyyjavpevabtveksdbyfwhmtxvbxbuhxpuutmqfxrrpazbpijaskmhnunntpojdfkppmrhwvvnicthcxhnpjmrgmuwuwqfhwgssdmcgiekgftestjzupqjnakclpmzazaghkosnutqekzlixovhabfsspqbwfvvenygtvmwmrqxnsqejekhzcziwgtyovpyukgcpjzxeqxjvaiffwlgiyzsmztqhmxoqolhblqhxeararaljnswlwdcfxlmehqraoobydhprasgtsesugkyqbexiilmvupjvkbmsmjqgtsylhpaeyhbwbbhrpgazokrlzcibhnbpomieavawiomsfzzkwkndihwzhrpiafrsyufpzblzpvflywmaweprthnkajvplkwfjvcsiblvucjmwcjkwsszhggczzcsfrzgadkasghstkknguodxxhzftrfrnlbrwpwrjlsecvrarjvgciymaincafmlphlibteuzhrfnldcajimjxqomljxweqhyiqecyznpnsuzzldrladelaqoqgiagjhjnsdrmlrldzebcvqxqdthxvhmzcmyczekvymbnyisppljimozszqqxymqkejfewxxihupebmydhlqldrzafehscklchzjlctmuaytuhosxruqanpchvjptbykpezxikaueufuiiujmanodulozjamqduqekihdmeizqcdtfihvvjrxoazgibfhoumqriiorsbbkoscxviabqddeqfayfzqptamhojdmxbpyubixhgdhqtmtcvjzdutvbiycsmchgkaeiaxbpgkpreuhoisfptugogbquijkxnyntfututflaacniiawxbxdsghavtenvatfyfkjkeisactvkmweotubudbekwkbhctxlqabxawclzftxqyvmdaptphftdyfspdwruohjdwsbjtjkmyaabxwrosyeswoygiilbmefqhmuhkvmgljiucorrximtkwdlcmceytuyyrmcbembghmrdzcgxgbzbcscezqamnhnkuecjehouthtpqzeuibiruvneafgizllkntztgksnvtcqklhcyvvrixabwekbjdvezwfjmdrmhiabvnwwanjxbiwhmtgjfjhofpqliigrsnfehmrpjsxsmxvgrwnmpvfxaxzkrzbqccmwizqgaousmehamsdmvibzeslwbolrfxcggviotkytewihiffdwsujqmszzoxhrnktdwefkxtnratgtgnjxjhscuqysuaeuecmsdjdbuvtemhsyygvryfqrlccstckgmtfxtiumvvgwbxotlyogvsmahfcubuywihnchkxhfexfsxteysowunucuqtjwmnnujihqecemszblrzyxmaupkjzgonsvszcslpcwluijfdrfqplpaxjcmhnwbtrlypqpguhhqosmldjtupwhfqlmwikvfruqylvkbwdfmtgcvmidiqtwigrcwdphloerrcsufbgjrulwweolbryzjbnydbjsulwawtibpxfxgtnoiomfnwjdqvjuzwfcbubuoyunlbsrdjvmccyutjksduphzyzeuxdnmejlcwzhktaudwapqragthmvclwvrrlwfqxbstmotxjelykcthiwoeobyuvirzpikyhuxqbfwfyspzghjddvjjrctqpvuckeessrlwzznhlmfnxxuhsrntxqysyzvfumrjjybfvtubeofcfsdimcjcunfconixdcckquifqetcoevhtzqqgtrgjlhfrxfrmzrkdrehbjmcsegbgnfwvfwqtjfalftldgzemgsntnpohnmjjfrlkkktxmjynayhqwfiqvjdqdcqhjhcgnviefsrblfvmrjdgmwkajeftvfvrljswjcvmismwxoqzqrpelaswotetaruqvmqrfjfgcnmtafpvjkrfdhibwvbdvlypvpfjnyxllldutrqkuiikkxkccnvxkkcdmlvsoududwmszpcrxfyckgdnhxvbhipxailopjpagjtssubjqryszvakdzmqqensqpmlobdohunwmqdvsexcotpmbdnrzjozymmahpvxrfvqjyppkguqeqfjzqquunjucpklshfizqsdsozcfhroomsceknndlakucrsyfkkjeauuhblcwfubtatghwjwylgtixidghdkpwsxvyucwzjovegwuzmdmzdzipapaftthkxcqzhbxzuxdysmydkqxdzoiwvlcllkfqrplmmzlvdafrvujssdjlosjhxrmkolygnmhafjzsoqzzgqixbblfeakrqzcozpfhaldatxdawaencurqlkqmontijupsaxpdzuodecpztnsfvgtxxsnlqhuxojdllylacuknrpelcxlfqrnohnzynmvmrymndpraehvdzpyqbfcqpoospnnumxvbjkfximgpzfvqkxixcccxkpsbebarqjlnoruguynbqjnsyqatwmxjxkinemdscabmvjepayznbsnrcvwnsiwciaeyurrzxspaggwtbcwcgcxygzyvaqsiuemwqfigqoiupelteadpkmtrjzsfcmtdnbxviagxxxjfnyxkfpoypzewzqyjwynavgvxkdmmklbupcvswmfgjszfttodzpjjzdpmcuprzkzgkawsjttitwsmlfzveqpsnreurbxktxbnhopghituwzdqreqixlrjyflambpwtvauuqwdiihxdvvgmudztstoasyznviqclgrkfooxiaftlfgafcvqzqvvgqnteruftasazvqqltgyezacmjolusiyfaptyaugprvrmdadpkkqjzzyuuiajdojrwnvcsyrbilfkwsthlatekadqwrbexptujelyjlhckgzodzegnwavhjtzdhgngaygylxunyitnnbhfzrcqrbedkydkotnlaxxivreyqzprtoqifuglaneimgtltxtvabeyhowyhvercjscsjtcvbihorrcprfhwlkfplfvxvwydlqlfxksvjspyzjbsituzbawcushnrpbqtsybjuwdhwmilcmyhocyafcxdwmtnjdgribthfgjcvvdgggmevoujuxebbdgjymfcssrocrfefzhjajcaggezbvzfnajjrdsswvnlfhmbemxiibvbbisrpdaecvgexdhanenawkxfdesvqvjkxtjwfprmcqgizqjakkvbqszfexgrkhqsbvpagulmkeltzlldflzlwfluxjtrzgyturuvngqsdwwjvnvesingccnmgydwpxqxszhwcpiilkwtlbkoqkgxidomcmwhpbispyntpwydcljijcxpgbdquiangjcsgqerddvwbasrokfwttzcwvxwctzqqeizkazcvilyaqiwpgtresrvmmsovmngszwxqgsicuavurejrxqhqhdogizjyrgtscrswuqduludhpqoaqgoremhcwothfxtwamlpbjuxknaootmgrgqwsfviauavltgjmnewwampfkxgnptbtwlvephmqjitrbqizhkxpbltpirxvkbeeytrjfjyvfkxpoydfopgkfogrbwkruirmpztudohctalqnlwjnjgxhrnlcfrtbnaaxheaedkhubxlylvxgjicisijslypysyyrxhveknlpswcveggzypxtouftekmktmbhzmjxijgegrelttuzxgxeontzylnmadtygmgfrwjdxavcahctbfrwgpizvygtrilecddmihbacugavkpqxunwtzxakssyfqixpqsohxpznknrptsijjvfrqwafhzqedbevybbcwlrcinnqmonigwmmcfteehdjnpmivzarzjlsswdzwdyojliqyxasploqcuowsnepemzsrasnrwxudbozpiaawvfkmiibjpbmjptavrzjaxvqdpdbjavhzmdyoooqwaxualbxbbwlnxyclxrmrrsbczbelkgmszbtarhjzyptkhtmekbigdduhfuqokqabgbdwoyewvsdbgthcxlefmcglnkghioigivsyirhtrmtcygsvboykbbxrrxqtghtztwmguoojyskkovsswxuqsbevfxexaddndjamwnmwlqfniuzvgwddwaaktkuhsmegkklakvcphurrctywbwnwuzfhrsqpmcxrcqopiyhrrtoyrlgkeyusswndesokqsjhsyveioagkkiftwwkdwmastkhvnvnpxyrjvuavwbahtzanolkzviqhduoznybklsipqquhvhevpyfnbixivtaqdsfi")
                .ShouldBeTrue();
        }
    }
}